version: '3'
services:
  db:
    image: postgres
    container_name: memory_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: memorygame
    ports:
      - "5456:5432"
    restart: always
    network_mode: bridge
    volumes:
      - ./db/createTable.sql:/docker-entrypoint-initdb.d/createTable.sql